web:
  build: .
  command: "bash -c 'npm install; node src/app.js'"
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - "8080:8080"
  volumes:
    - ./:/app/user/
    - /app/user/node_modules
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - "8080:8080"
  volumes:
    - ".:/app/user"
